### ISSUE TITLE
bug: element-visible.ts 17 

### ISSUE THREAD

**Issue by lzm420241** [ng2-ui/ng2-utils#1]
code: `(typeof innerElement === 'string') ?
    (innerEl = <HTMLElement>document.querySelector(<string>innerElement)) : innerElement;`

the code i think should be: 
`(typeof innerElement === 'string') ?
    (innerEl = <HTMLElement>document.querySelector(<string>innerElement)) : (innerEl = innerElement);`

**Comment by allenhwkim** [comment]
Thanks, I have updated the code. Will be released later.
