### ISSUE TITLE
scrollTo() accuracy

### ISSUE THREAD

**Issue by buk-jungho** [ng2-ui/ng2-utils#4]
Since 'step' is calculated with Math.ceil, it sometimes has rounded value, which results incorrect final position after scroll.

Would the line 61 in scroll-to.ts should be changed from:
> i > 1 && loop(i - 1, prop);

to something like this?:
> i > 1 ? loop(i - 1, prop) :
          horizontal ?
            scrollContainerEl[prop] = targetOffsetLeft
            : scrollContainerEl[prop] = targetOffsetTop;

which will force set the last position to target offset.

I am pretty new to angular/javascript world, so please let me know if I am thinking wrong.

**Comment by allenhwkim** [comment]
@buk-jungho thanks for the feedback. This will be looked into later. 
A PR, Pull Request, would be appreciated if you find a solution.

**Comment by allenhwkim** [comment]
```
  // start scrolling
  let step = horizontal ?
    Math.ceil((targetOffsetLeft - currentScrollLeft) / 10) :
    Math.ceil((targetOffsetTop - currentScrollTop) / 10);
  let scrollProp = horizontal ? 'scrollLeft' : 'scrollTop';
  (function loop(i: number, prop: any): void {
    setTimeout(function main() {
      scrollContainerEl[prop] += step;
      if (i > 1) {
        loop(i - 1, prop);
      } else {  //the last step
        scrollContainerEl[prop] = horizontal ? targetOffsetLeft : targetOffsetTop;
      }
    }, 50);
  }(10, scrollProp));
```

This will work?

**Comment by buk-jungho** [comment]
It looks great. Looks much clear than what I suggested. I'd appreciate if you put this in the future release.
